/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Principal;

/**
 *
 * @author Acer
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpnContenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmitemRegistrarEmpleado = new javax.swing.JMenuItem();
        jmitemRegistrarCitas = new javax.swing.JMenuItem();
        jmitemRegistrarMedicamentos = new javax.swing.JMenuItem();
        jMenuMascotas = new javax.swing.JMenu();
        jmitemRegistrarCliente = new javax.swing.JMenuItem();
        jmitemRegistrarMascota = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmitemReporteCitas = new javax.swing.JMenuItem();
        jmitemReporteEmpleados = new javax.swing.JMenuItem();
        jmitemReporteClientes = new javax.swing.JMenuItem();
        jmitemReporteMascotas = new javax.swing.JMenuItem();
        jmitemReporteMedicamentos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpnContenedorLayout = new javax.swing.GroupLayout(jdpnContenedor);
        jdpnContenedor.setLayout(jdpnContenedorLayout);
        jdpnContenedorLayout.setHorizontalGroup(
            jdpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jdpnContenedorLayout.setVerticalGroup(
            jdpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jMenu2.setText("Veterinaria");

        jmitemRegistrarEmpleado.setText("Registrar Empleados");
        jmitemRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitemRegistrarEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(jmitemRegistrarEmpleado);

        jmitemRegistrarCitas.setText("Registrar Citas");
        jmitemRegistrarCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitemRegistrarCitasActionPerformed(evt);
            }
        });
        jMenu2.add(jmitemRegistrarCitas);

        jmitemRegistrarMedicamentos.setText("Registrar Medicamentos");
        jmitemRegistrarMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitemRegistrarMedicamentosActionPerformed(evt);
            }
        });
        jMenu2.add(jmitemRegistrarMedicamentos);

        jMenuBar1.add(jMenu2);

        jMenuMascotas.setText("Mascotas");

        jmitemRegistrarCliente.setText("Registrar Cliente");
        jMenuMascotas.add(jmitemRegistrarCliente);

        jmitemRegistrarMascota.setText("Registrar Mascota");
        jmitemRegistrarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitemRegistrarMascotaActionPerformed(evt);
            }
        });
        jMenuMascotas.add(jmitemRegistrarMascota);

        jMenuBar1.add(jMenuMascotas);

        jMenu1.setText("Reportes");

        jmitemReporteCitas.setText("Citas");
        jMenu1.add(jmitemReporteCitas);

        jmitemReporteEmpleados.setText("Empleados");
        jmitemReporteEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitemReporteEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(jmitemReporteEmpleados);

        jmitemReporteClientes.setText("Clientes");
        jMenu1.add(jmitemReporteClientes);

        jmitemReporteMascotas.setText("Mascotas");
        jMenu1.add(jmitemReporteMascotas);

        jmitemReporteMedicamentos.setText("Medicamentos");
        jMenu1.add(jmitemReporteMedicamentos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpnContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpnContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmitemRegistrarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitemRegistrarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitemRegistrarMascotaActionPerformed

    private void jmitemRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitemRegistrarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitemRegistrarEmpleadoActionPerformed

    private void jmitemReporteEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitemReporteEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitemReporteEmpleadosActionPerformed

    private void jmitemRegistrarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitemRegistrarCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitemRegistrarCitasActionPerformed

    private void jmitemRegistrarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitemRegistrarMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitemRegistrarMedicamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuMascotas;
    public javax.swing.JDesktopPane jdpnContenedor;
    public javax.swing.JMenuItem jmitemRegistrarCitas;
    public javax.swing.JMenuItem jmitemRegistrarCliente;
    public javax.swing.JMenuItem jmitemRegistrarEmpleado;
    public javax.swing.JMenuItem jmitemRegistrarMascota;
    public javax.swing.JMenuItem jmitemRegistrarMedicamentos;
    public javax.swing.JMenuItem jmitemReporteCitas;
    public javax.swing.JMenuItem jmitemReporteClientes;
    public javax.swing.JMenuItem jmitemReporteEmpleados;
    public javax.swing.JMenuItem jmitemReporteMascotas;
    public javax.swing.JMenuItem jmitemReporteMedicamentos;
    // End of variables declaration//GEN-END:variables
}
