/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Principal;

/**
 *
 * @author Acer
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpnContenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuMascotas = new javax.swing.JMenu();
        jmitemRegistrarCliente = new javax.swing.JMenuItem();
        jmitemRegistrarMascota = new javax.swing.JMenuItem();
        jmitemModificarMascotas = new javax.swing.JMenuItem();
        jmitemModificarClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpnContenedorLayout = new javax.swing.GroupLayout(jdpnContenedor);
        jdpnContenedor.setLayout(jdpnContenedorLayout);
        jdpnContenedorLayout.setHorizontalGroup(
            jdpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        jdpnContenedorLayout.setVerticalGroup(
            jdpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jMenu2.setText("Veterinaria");
        jMenuBar1.add(jMenu2);

        jMenuMascotas.setText("Mascotas");

        jmitemRegistrarCliente.setText("Registrar Cliente");
        jMenuMascotas.add(jmitemRegistrarCliente);

        jmitemRegistrarMascota.setText("Registrar Mascota");
        jmitemRegistrarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitemRegistrarMascotaActionPerformed(evt);
            }
        });
        jMenuMascotas.add(jmitemRegistrarMascota);

        jmitemModificarMascotas.setText("Modificar Mascotas");
        jmitemModificarMascotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitemModificarMascotasActionPerformed(evt);
            }
        });
        jMenuMascotas.add(jmitemModificarMascotas);

        jmitemModificarClientes.setText("Modificar Clientes");
        jmitemModificarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitemModificarClientesActionPerformed(evt);
            }
        });
        jMenuMascotas.add(jmitemModificarClientes);

        jMenuBar1.add(jMenuMascotas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpnContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpnContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmitemRegistrarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitemRegistrarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitemRegistrarMascotaActionPerformed

    private void jmitemModificarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitemModificarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitemModificarClientesActionPerformed

    private void jmitemModificarMascotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitemModificarMascotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitemModificarMascotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuMascotas;
    public javax.swing.JDesktopPane jdpnContenedor;
    public javax.swing.JMenuItem jmitemModificarClientes;
    public javax.swing.JMenuItem jmitemModificarMascotas;
    public javax.swing.JMenuItem jmitemRegistrarCliente;
    public javax.swing.JMenuItem jmitemRegistrarMascota;
    // End of variables declaration//GEN-END:variables
}
