/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistaPrincipal;

/**
 *
 * @author Acer
 */
public class frmInicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_registrarEspecie = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_registrarTipoCita = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registrarEspecie.setBackground(new java.awt.Color(204, 255, 204));
        btn_registrarEspecie.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_registrarEspecie.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrarEspecie.setText("REGISTRAR");
        btn_registrarEspecie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_registrarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarEspecieActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrarEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 110, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRAR NUEVO TIPO DE CITA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PATITAS DE NO SE QUE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        btn_registrarTipoCita.setBackground(new java.awt.Color(204, 255, 204));
        btn_registrarTipoCita.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_registrarTipoCita.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrarTipoCita.setText("REGISTRAR");
        btn_registrarTipoCita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_registrarTipoCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarTipoCitaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrarTipoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 110, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("REGISTRAR NUEVA ESPECIE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarTipoCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarTipoCitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarTipoCitaActionPerformed

    private void btn_registrarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarEspecieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_registrarEspecie;
    public javax.swing.JButton btn_registrarTipoCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
