/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaPrincipal;

/**
 *
 * @author Acer
 */
public class frmRegistrarEspecie extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarEspecie
     */
    public frmRegistrarEspecie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_RCitas = new javax.swing.JTable();
        txt_nombreEspecie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_IdEspecie = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_Consultar = new javax.swing.JButton();
        btn_Consultar1 = new javax.swing.JButton();
        btn_Consultar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_RCitas.setBackground(new java.awt.Color(255, 255, 255));
        tbl_RCitas.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_RCitas.setForeground(new java.awt.Color(0, 0, 0));
        tbl_RCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_RCitas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, 230));

        txt_nombreEspecie.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombreEspecie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_nombreEspecie.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombreEspecie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "NOMBRE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txt_nombreEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreEspecieActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombreEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 50));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nueva Especie");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        txt_IdEspecie.setBackground(new java.awt.Color(255, 255, 255));
        txt_IdEspecie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_IdEspecie.setForeground(new java.awt.Color(0, 0, 0));
        txt_IdEspecie.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        txt_IdEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdEspecieActionPerformed(evt);
            }
        });
        jPanel1.add(txt_IdEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 110, 50));

        btn_guardar.setBackground(new java.awt.Color(204, 255, 204));
        btn_guardar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(0, 0, 0));
        btn_guardar.setText("REGISTRAR");
        btn_guardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 100, 40));

        btn_Consultar.setBackground(new java.awt.Color(204, 204, 255));
        btn_Consultar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_Consultar.setForeground(new java.awt.Color(0, 0, 0));
        btn_Consultar.setText("CONSULTAR");
        btn_Consultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 30));

        btn_Consultar1.setBackground(new java.awt.Color(255, 204, 204));
        btn_Consultar1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_Consultar1.setForeground(new java.awt.Color(0, 0, 0));
        btn_Consultar1.setText("ELIMINAR");
        btn_Consultar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Consultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Consultar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Consultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 100, 30));

        btn_Consultar2.setBackground(new java.awt.Color(204, 255, 255));
        btn_Consultar2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_Consultar2.setForeground(new java.awt.Color(0, 0, 0));
        btn_Consultar2.setText("ACTUALIZAR");
        btn_Consultar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Consultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Consultar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Consultar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 259, 479));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreEspecieActionPerformed

    private void txt_IdEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdEspecieActionPerformed

    private void btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ConsultarActionPerformed

    private void btn_Consultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Consultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Consultar1ActionPerformed

    private void btn_Consultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Consultar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Consultar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarEspecie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrarEspecie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Consultar;
    public javax.swing.JButton btn_Consultar1;
    public javax.swing.JButton btn_Consultar2;
    public javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbl_RCitas;
    public javax.swing.JTextField txt_IdEspecie;
    public javax.swing.JTextField txt_nombreEspecie;
    // End of variables declaration//GEN-END:variables
}
