/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Acer
 */
public class frmReporteMedicamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReporteMedicamento
     */
    public frmReporteMedicamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_pricipio_Activo = new javax.swing.JTextField();
        cbx_TipoMedicamento = new javax.swing.JComboBox<>();
        cbx_funcionTerapeutica = new javax.swing.JComboBox<>();
        jdtc_FechaVencimiento = new com.toedter.calendar.JDateChooser();
        cbx_TipoBusqueda = new javax.swing.JComboBox<>();
        btn_consultar = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        btn_exportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_RPMedicamento = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1280, 620));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REPORTE MEDICAMENTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        txt_pricipio_Activo.setBackground(new java.awt.Color(255, 255, 255));
        txt_pricipio_Activo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_pricipio_Activo.setForeground(new java.awt.Color(0, 0, 0));
        txt_pricipio_Activo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "PRINCIPIO ACTIVO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.add(txt_pricipio_Activo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 180, 50));

        cbx_TipoMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        cbx_TipoMedicamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbx_TipoMedicamento.setForeground(new java.awt.Color(0, 0, 0));
        cbx_TipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_TipoMedicamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "TIPO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.add(cbx_TipoMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 150, 50));

        cbx_funcionTerapeutica.setBackground(new java.awt.Color(255, 255, 255));
        cbx_funcionTerapeutica.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbx_funcionTerapeutica.setForeground(new java.awt.Color(0, 0, 0));
        cbx_funcionTerapeutica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_funcionTerapeutica.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "FUNCION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.add(cbx_funcionTerapeutica, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 170, 50));

        jdtc_FechaVencimiento.setBackground(new java.awt.Color(255, 255, 255));
        jdtc_FechaVencimiento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "FECHA VENCIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jdtc_FechaVencimiento.setForeground(new java.awt.Color(0, 153, 0));
        jPanel1.add(jdtc_FechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 170, 50));

        cbx_TipoBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        cbx_TipoBusqueda.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbx_TipoBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        cbx_TipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_TipoBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "TIPO DE BUSQUEDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.add(cbx_TipoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 150, 50));

        btn_consultar.setBackground(new java.awt.Color(204, 255, 204));
        btn_consultar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_consultar.setForeground(new java.awt.Color(0, 0, 0));
        btn_consultar.setText("CONSULTAR");
        btn_consultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(btn_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, 110, 40));

        btn_nuevo.setBackground(new java.awt.Color(204, 255, 255));
        btn_nuevo.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(0, 0, 0));
        btn_nuevo.setText("NUEVO");
        btn_nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 80, 80, 40));

        btn_exportar.setBackground(new java.awt.Color(255, 204, 255));
        btn_exportar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btn_exportar.setForeground(new java.awt.Color(0, 0, 0));
        btn_exportar.setText("EXPORTAR");
        btn_exportar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 80, 100, 40));

        tbl_RPMedicamento.setBackground(new java.awt.Color(255, 255, 255));
        tbl_RPMedicamento.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbl_RPMedicamento.setForeground(new java.awt.Color(0, 0, 0));
        tbl_RPMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_RPMedicamento);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 1180, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_consultar;
    public javax.swing.JButton btn_exportar;
    public javax.swing.JButton btn_nuevo;
    public javax.swing.JComboBox<String> cbx_TipoBusqueda;
    public javax.swing.JComboBox<String> cbx_TipoMedicamento;
    public javax.swing.JComboBox<String> cbx_funcionTerapeutica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public com.toedter.calendar.JDateChooser jdtc_FechaVencimiento;
    public javax.swing.JTable tbl_RPMedicamento;
    public javax.swing.JTextField txt_pricipio_Activo;
    // End of variables declaration//GEN-END:variables
}
